services:
  app:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "4173:4173"
    command: sh -c "npm install && npm run build && npm run preview -- --host 0.0.0.0"

name: portofolio-react